### ISSUE TITLE
After update to 0.3.0, any thermostat doesn't work in HA  

### ISSUE THREAD

**Issue by andriuk** [jvitkauskas/homeassistant_salus#19]
Dear @jvitkauskas  
Today I updated pyit600 to 0.3.0, but after the restart, all thermostats are not available. 

This message show in logs : 

Logger: pyit600
Source: /usr/local/lib/python3.9/site-packages/pyit600/gateway.py:544
First occurred: 14:36:08 (1298 occurrences)
Last logged: 14:54:25

Failed to poll device 001e5e09026820c2
Failed to poll device 001e5e0902681f37
Failed to poll device 001e5e09026821a6
Failed to poll device 001e5e090208ed91
Failed to poll device 001e5e0902518e08
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyit600/gateway.py", line 500, in _refresh_climate_devices
    device = ClimateDevice(
TypeError: <lambda>() missing 3 required positional arguments: 'fan_mode', 'fan_modes', and 'locked'

**Comment by maymaymay** [comment]
My termostats also not working:
2021-09-28 06:13:16 ERROR (MainThread) [pyit600] Failed to poll device 001e5e090208eeca
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyit600/gateway.py", line 500, in _refresh_climate_devices
device = ClimateDevice(
TypeError: <lambda>() missing 3 required positional arguments: 'fan_mode', 'fan_modes', and 'locked'
2021-09-28 06:13:16 ERROR (MainThread) [pyit600] Failed to poll device 001e5e090208f361
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyit600/gateway.py", line 500, in _refresh_climate_devices
device = ClimateDevice(
TypeError: <lambda>() missing 3 required positional arguments: 'fan_mode', 'fan_modes', and 'locked'
2021-09-28 06:13:16 ERROR (MainThread) [pyit600] Failed to poll device 001e5e090208ed34
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyit600/gateway.py", line 500, in _refresh_climate_devices
device = ClimateDevice(
TypeError: <lambda>() missing 3 required positional arguments: 'fan_mode', 'fan_modes', and 'locked'
2021-09-28 06:13:16 ERROR (MainThread) [pyit600] Failed to poll device 001e5e090208f497
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyit600/gateway.py", line 500, in _refresh_climate_devices
device = ClimateDevice(
TypeError: <lambda>() missing 3 required positional arguments: 'fan_mode', 'fan_modes', and 'locked'
2021-09-28 06:13:16 ERROR (MainThread) [pyit600] Failed to poll device 001e5e090208f610
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyit600/gateway.py", line 500, in _refresh_climate_devices
device = ClimateDevice(
TypeError: <lambda>() missing 3 required positional arguments: 'fan_mode', 'fan_modes', and 'locked'
2021-09-28 06:13:16 ERROR (MainThread) [pyit600] Failed to poll device 001e5e090208f186
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyit600/gateway.py", line 500, in _refresh_climate_devices
device = ClimateDevice(
TypeError: <lambda>() missing 3 required positional arguments: 'fan_mode', 'fan_modes', and 'locked'

**Comment by jvitkauskas** [comment]
Sorry that I didn't test it when merging changes. Can you please try version 0.3.1?

**Comment by maymaymay** [comment]
Hi  @jvitkauskas now with 0.3.1 its working again.
Thank YOU!

**Comment by jvitkauskas** [comment]
Thanks. Closing.
